using System.ComponentModel.DataAnnotations;
using FlowFlex.Domain.Entities.Base;
using SqlSugar;
using Newtonsoft.Json;
using FlowFlex.Domain.Shared.JsonConverters;

namespace FlowFlex.Domain.Entities.OW
{
    /// <summary>
    /// Document Snapshot Entity - Stores Univer document data (IWorkbookData / IDocumentData JSON)
    /// </summary>
    [SugarTable("ff_document_snapshot")]
    public class DocumentSnapshot : EntityBaseCreateInfo
    {
        /// <summary>
        /// Univer document unique ID (UUID generated by frontend)
        /// </summary>
        [StringLength(100)]
        [SugarColumn(ColumnName = "unit_id")]
        public string UnitId { get; set; }

        /// <summary>
        /// Document title
        /// </summary>
        [StringLength(200)]
        public string Title { get; set; }

        /// <summary>
        /// Document type: Sheet / Doc / Slide
        /// </summary>
        [StringLength(20)]
        [SugarColumn(ColumnName = "doc_type")]
        public string DocType { get; set; } = "Sheet";

        /// <summary>
        /// Document snapshot JSON (IWorkbookData / IDocumentData).
        /// Stored as JSONB in PostgreSQL. C# type is string.
        /// SqlSugar IsJson = true is required so it sends the value as JSONB, not text.
        /// </summary>
        [SugarColumn(ColumnName = "data_json", ColumnDataType = "jsonb", IsJson = true)]
        public string DataJson { get; set; }

        /// <summary>
        /// Revision number for collaborative editing (starts at 1, increments on each Ingest)
        /// </summary>
        public int Revision { get; set; } = 1;

        /// <summary>
        /// Associated business entity type (e.g. "Onboarding", "Stage") — optional
        /// </summary>
        [StringLength(50)]
        [SugarColumn(ColumnName = "entity_type")]
        public string EntityType { get; set; }

        /// <summary>
        /// Associated business entity ID — optional
        /// </summary>
        [SugarColumn(ColumnName = "entity_id")]
        [JsonConverter(typeof(LongToStringConverter))]
        public long EntityId { get; set; }
    }
}
