namespace FlowFlex.Domain.Shared.Enums
{
    public static class CategoryType
    {
        public const string EDIT_BASIC = "EDIT:BASIC";
        public const string EDIT_CONTRACTINFO = "EDIT:CONTRACTINFO";
        public const string EDIT_DETAILS = "EDIT:DETAILS";
        public const string EDIT_ADDRESSES = "EDIT:ADDRESSES";
        public const string EDIT_BILLING = "EDIT:BILLING";
        public const string EDIT_FILE = "EDIT:FILE";
        public const string EDIT_PROGRAMATTRIBUTE = "EDIT:PROGRAMATTRIBUTE";
        public const string EDIT_BANKPAYMENTDETAILS = "EDIT:BANKPAYMENTDETAILS";
        public const string EDIT_RELATIONSHIPSCONTACTS = "EDIT:RELATIONSHIPSCONTACTS";
        public const string EDIT_ACCOUNTHOLDERS = "EDIT:ACCOUNTHOLDERS";
        public const string EDIT_FINANCIA = "EDIT:FINANCIA";
        public const string EDIT_CREDITAPPLICATIONS = "EDIT:CREDITAPPLICATIONS";
        public const string EDIT_NOTES = "EDIT:NOTES";
        public const string EDIT_BANKPAYMENTDETAILSDEBIT = "EDIT:BANKPAYMENTDETAILSDEBIT";
        public const string EDIT_BANKPAYMENTDETAILSCREDIT = "EDIT:BANKPAYMENTDETAILSCREDIT";
        public const string EDIT_OPERATIONALATTRIBUTESBASICINFO = "EDIT:OPERATIONALATTRIBUTESBASICINFO";
        public const string EDIT_OPERATIONALATTRIBUTESINBOUND = "EDIT:OPERATIONALATTRIBUTESINBOUND";
        public const string EDIT_OPERATIONALATTRIBUTESOUTBOUND = "EDIT:OPERATIONALATTRIBUTESOUTBOUND";
        public const string EDIT_OPERATIONALATTRIBUTESSTOCKROTATION = "EDIT:OPERATIONALATTRIBUTESSTOCKROTATION";
        public const string EDIT_REFERENCETRADEREFERENCE = "EDIT:REFERENCETRADEREFERENCE";
        public const string EDIT_REFERENCEPERSONALGUARANTEE = "EDIT:REFERENCEPERSONALGUARANTEE";

        public const string EDIT_DEALS = "EDIT:DEALS";
        public const string EDIT_LEADS_CONTACTS = "EDIT:LEADS:CONTACTS";
        public const string EDIT_LEADS_COMPANIES = "EDIT:EDIT:LEADS:COMPANIES";

    }
}
