using System.ComponentModel.DataAnnotations;
using FlowFlex.Domain.Shared.Enums.Action;
using Item.Common.Lib.JsonConverts;
using Item.Excel.Lib;
using Newtonsoft.Json;

namespace FlowFlex.Application.Contracts.Dtos.Action
{
    /// <summary>
    /// Action definition DTO for CRUD operations
    /// </summary>
    public class ActionDefinitionDto
    {
        /// <summary>
        /// Action definition ID
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// Action code
        /// </summary>
        [ExcelColumn(Name = "Action Code")]
        public string ActionCode { get; set; }

        /// <summary>
        /// Action name
        /// </summary>
        [Required]
        [StringLength(100)]
        [ExcelColumn(Name = "Action Name")]
        public string Name { get; set; }

        /// <summary>
        /// Action description
        /// </summary>
        [StringLength(500)]
        [ExcelColumn(Name = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Action type
        /// </summary>
        [Required]
        [ExcelColumn(Name = "Action Type", MapType = typeof(ActionTypeEnum))]
        public ActionTypeEnum ActionType { get; set; }

        /// <summary>
        /// Action configuration (JSON format)
        /// </summary>
        [Required]
        public string ActionConfig { get; set; }

        /// <summary>
        /// Whether the action is enabled
        /// </summary>
        public bool IsEnabled { get; set; } = true;

        /// <summary>
        /// Creation time
        /// </summary>
        [ExcelColumn(Name = "Create Date", Format = "dd/MM/yyyy HH:mm:ss")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Last update time
        /// </summary>
        public DateTime UpdatedAt { get; set; }

        public bool IsTools { get; set; }

        /// <summary>
        /// Whether this action was generated by AI
        /// </summary>
        public bool IsAIGenerated { get; set; } = false;

        /// <summary>
        /// Trigger type for the action (Stage, Task, Question, Workflow)
        /// Defines where this action can be used or triggered
        /// </summary>
        public string TriggerType { get; set; }

        /// <summary>
        /// Trigger mappings with related entity details
        /// </summary>
        public List<ActionTriggerMappingInfo> TriggerMappings { get; set; } = new();

        /// <summary>
        /// Integration ID - associated integration for this action
        /// </summary>
        public long? IntegrationId { get; set; }

        /// <summary>
        /// Integration name
        /// </summary>
        public string? IntegrationName { get; set; }

        /// <summary>
        /// Data direction configuration
        /// </summary>
        public DataDirectionDto DataDirection { get; set; } = new();

        /// <summary>
        /// Field mappings associated with this action (when Integration is linked)
        /// </summary>
        public List<ActionFieldMappingDto>? FieldMappings { get; set; }
    }

    /// <summary>
    /// Data direction configuration DTO
    /// </summary>
    public class DataDirectionDto
    {
        /// <summary>
        /// Whether this action receives data from external system (Inbound)
        /// </summary>
        public bool Inbound { get; set; } = false;

        /// <summary>
        /// Whether this action sends data to external system (Outbound)
        /// </summary>
        public bool Outbound { get; set; } = false;
    }

    /// <summary>
    /// Action field mapping DTO for displaying field mappings associated with an action
    /// </summary>
    public class ActionFieldMappingDto
    {
        /// <summary>
        /// Field mapping ID
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// External system field name
        /// </summary>
        public string ExternalFieldName { get; set; } = string.Empty;

        /// <summary>
        /// WFE field ID
        /// </summary>
        public string WfeFieldId { get; set; } = string.Empty;

        /// <summary>
        /// WFE field display name
        /// </summary>
        public string WfeFieldName { get; set; } = string.Empty;

        /// <summary>
        /// Field data type (Text, Number, Date, Boolean, Lookup)
        /// </summary>
        public string FieldType { get; set; } = string.Empty;

        /// <summary>
        /// Sync direction (ViewOnly, Editable, OutboundOnly)
        /// </summary>
        public string SyncDirection { get; set; } = string.Empty;

        /// <summary>
        /// Whether this field is required
        /// </summary>
        public bool IsRequired { get; set; }

        /// <summary>
        /// Default value for this field
        /// </summary>
        public string? DefaultValue { get; set; }

        /// <summary>
        /// Sort order for display
        /// </summary>
        public int SortOrder { get; set; }
    }

    /// <summary>
    /// Action trigger mapping information for DTO
    /// </summary>
    public class ActionTriggerMappingInfo
    {
        /// <summary>
        /// Mapping ID
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// Trigger type (Stage, Task, Question)
        /// </summary>
        public string TriggerType { get; set; } = string.Empty;

        /// <summary>
        /// Trigger source ID
        /// </summary>
        public long TriggerSourceId { get; set; }

        /// <summary>
        /// Trigger source name
        /// </summary>
        public string TriggerSourceName { get; set; } = string.Empty;

        /// <summary>
        /// Workflow ID
        /// </summary>
        public long? WorkFlowId { get; set; }

        /// <summary>
        /// Workflow name
        /// </summary>
        public string WorkFlowName { get; set; } = string.Empty;

        /// <summary>
        /// Stage ID
        /// </summary>
        public long? StageId { get; set; }

        /// <summary>
        /// Stage name
        /// </summary>
        public string StageName { get; set; } = string.Empty;

        /// <summary>
        /// Trigger event
        /// </summary>
        public string TriggerEvent { get; set; } = string.Empty;

        /// <summary>
        /// Whether the mapping is enabled
        /// </summary>
        public bool IsEnabled { get; set; } = true;

        /// <summary>
        /// Execution order
        /// </summary>
        public int ExecutionOrder { get; set; } = 0;

        /// <summary>
        /// Description
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Last applied
        /// </summary>
        [JsonConverter(typeof(DateTimeJsonConverter))]
        public DateTimeOffset? LastApplied { get; set; }
    }
}