using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using FlowFlex.Application.Contracts.Dtos.OW.Stage;
using FlowFlex.Domain.Shared.Enums.OW;

namespace FlowFlex.Application.Contracts.Dtos.OW.Workflow
{
    /// <summary>
    /// Workflow create/update input DTO
    /// </summary>
    public class WorkflowInputDto
    {
        /// <summary>
        /// 流程名称
        /// </summary>

        [StringLength(100)]
        public string Name { get; set; }

        /// <summary>
        /// 流程描述
        /// </summary>
        [StringLength(500)]
        public string Description { get; set; }

        /// <summary>
        /// 是否为默认流程
        /// </summary>
        public bool IsDefault { get; set; }

        /// <summary>
        /// 流程状态（active/inactive）
        /// </summary>
        [StringLength(20)]
        public string Status { get; set; } = "active";

        /// <summary>
        /// 开始日期
        /// </summary>
        public DateTimeOffset StartDate { get; set; }

        /// <summary>
        /// 结束日期（可空，默认流程不可填写）
        /// </summary>
        public DateTimeOffset? EndDate { get; set; }

        /// <summary>
        /// 是否激活
        /// </summary>
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// Whether this workflow was generated by AI
        /// </summary>
        public bool IsAIGenerated { get; set; } = false;

        /// <summary>
        /// Workflow version
        /// </summary>
        public int Version { get; set; } = 1;

        /// <summary>
        /// JSON for workflow configuration (stages, settings, etc.)
        /// </summary>
        public string? ConfigJson { get; set; }

        /// <summary>
        /// Visible in Portal
        /// </summary>
        public bool VisibleInPortal { get; set; } = true;

        /// <summary>
        /// Portal Permission - Viewable or Completable
        /// </summary>
        public PortalAvailabilityEnum? PortalPermission { get; set; } = PortalAvailabilityEnum.Viewable;

        /// <summary>
        /// View Permission Mode - Public/VisibleToTeams/InvisibleToTeams
        /// </summary>
        public ViewPermissionModeEnum ViewPermissionMode { get; set; } = ViewPermissionModeEnum.Public;

        /// <summary>
        /// View Teams - List of team names for view permission control
        /// </summary>
        public List<string>? ViewTeams { get; set; }

        /// <summary>
        /// Operate Teams - List of team names that can perform operations
        /// </summary>
        public List<string>? OperateTeams { get; set; }

        /// <summary>
        /// Use Same Team For Operate - Indicates whether operate teams should use the same teams as view permission
        /// When true, OperateTeams will be automatically synchronized with ViewTeams
        /// </summary>
        public bool UseSameTeamForOperate { get; set; } = false;

        /// <summary>
        /// Runtime Use Same As Template - When true, Runtime Permission inherits from Template Permission.
        /// When false, the Runtime_* fields below are used independently.
        /// </summary>
        public bool RuntimeUseSameAsTemplate { get; set; } = true;

        /// <summary>
        /// Runtime View Permission Mode - Public/VisibleTo/InvisibleTo (no Private at this layer).
        /// Only effective when RuntimeUseSameAsTemplate = false.
        /// </summary>
        public ViewPermissionModeEnum RuntimeViewPermissionMode { get; set; } = ViewPermissionModeEnum.Public;

        /// <summary>
        /// Runtime View Teams - List of team IDs for Runtime view permission control.
        /// Only effective when RuntimeUseSameAsTemplate = false.
        /// </summary>
        public List<string>? RuntimeViewTeams { get; set; }

        /// <summary>
        /// Runtime Operate Teams - List of team IDs for Runtime operate permission control.
        /// Always an independent selector at the Workflow Runtime layer (no "Use same" flag).
        /// Only effective when RuntimeUseSameAsTemplate = false.
        /// </summary>
        public List<string>? RuntimeOperateTeams { get; set; }

        /// <summary>
        /// Stages to be created with this workflow
        /// </summary>
        public List<StageInputDto>? Stages { get; set; }
    }
}