using FlowFlex.Application.Contracts.Dtos.OW.Checklist;
using FlowFlex.Application.Contracts.Dtos.OW.Questionnaire;
using FlowFlex.Application.Contracts.Dtos.OW.Workflow;
using FlowFlex.Application.Contracts.IServices;
using FlowFlex.Application.Contracts.IServices.AI;
using FlowFlex.Domain.Shared;
using Microsoft.Extensions.Logging;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace FlowFlex.Application.Services.AI.Parsing
{
    /// <summary>
    /// Unified AI response parser implementation
    /// Centralizes all response parsing, JSON repair, fallback generation, and confidence scoring logic
    /// extracted from the various AIService partial classes
    /// </summary>
    public class AIResponseParser : IAIResponseParser, IScopedService
    {
        private readonly ILogger<AIResponseParser> _logger;

        public AIResponseParser(ILogger<AIResponseParser> logger)
        {
            _logger = logger;
        }

        #region Workflow Parsing

        /// <inheritdoc />
        public AIWorkflowGenerationResult ParseWorkflowResponse(string aiResponse)
        {
            _logger.LogInformation("ParseWorkflowResponse started, response length: {Length}", aiResponse.Length);
            var methodStartTime = DateTime.UtcNow;

            try
            {
                // Clean up markdown code blocks if present
                var cleanedResponse = aiResponse;
                if (cleanedResponse.Contains("```json"))
                {
                    cleanedResponse = cleanedResponse.Replace("```json", "").Replace("```", "").Trim();
                    _logger.LogInformation("Cleaned markdown code blocks from response");
                }
                else if (cleanedResponse.Contains("```"))
                {
                    cleanedResponse = cleanedResponse.Replace("```", "").Trim();
                    _logger.LogInformation("Cleaned generic code blocks from response");
                }

                // Try to parse JSON response from AI
                if (cleanedResponse.Contains("{") && cleanedResponse.Contains("}"))
                {
                    _logger.LogInformation("Found JSON content, extracting...");
                    var jsonStart = cleanedResponse.IndexOf('{');
                    var jsonEnd = cleanedResponse.LastIndexOf('}') + 1;
                    var jsonContent = cleanedResponse.Substring(jsonStart, jsonEnd - jsonStart);

                    // Fix common JSON issues from AI responses
                    jsonContent = FixJsonContent(jsonContent);

                    _logger.LogDebug("Deserializing JSON, content length: {Length}", jsonContent.Length);
                    _logger.LogDebug("JSON Preview: {JsonPreview}",
                        jsonContent.Length > 300 ? jsonContent.Substring(0, 300) + "..." : jsonContent);
                    var parsed = JsonSerializer.Deserialize<JsonElement>(jsonContent);

                    var workflow = new WorkflowInputDto
                    {
                        Name = parsed.TryGetProperty("name", out var nameEl) ? nameEl.GetString() : "AI Generated Workflow",
                        Description = parsed.TryGetProperty("description", out var descEl) ? descEl.GetString() : "Generated by AI",
                        IsActive = true,
                        IsAIGenerated = true
                    };

                    var stages = new List<AIStageGenerationResult>();
                    var checklists = new List<AIChecklistGenerationResult>();
                    var questionnaires = new List<AIQuestionnaireGenerationResult>();

                    if (parsed.TryGetProperty("stages", out var stagesEl) && stagesEl.ValueKind == JsonValueKind.Array)
                    {
                        var order = 1;
                        foreach (var stageEl in stagesEl.EnumerateArray())
                        {
                            var stage = new AIStageGenerationResult
                            {
                                Name = stageEl.TryGetProperty("name", out var sNameEl) ? sNameEl.GetString() : $"Stage {order}",
                                Description = stageEl.TryGetProperty("description", out var sDescEl) ? sDescEl.GetString() : "",
                                Order = order,
                                AssignedGroup = stageEl.TryGetProperty("assignedGroup", out var sGroupEl) ? sGroupEl.GetString() : "General",
                                EstimatedDuration = stageEl.TryGetProperty("estimatedDuration", out var sDurEl) && sDurEl.TryGetInt32(out var dur) ? dur : 1
                            };
                            stages.Add(stage);

                            // Parse embedded checklist
                            if (stageEl.TryGetProperty("checklist", out var checklistEl))
                            {
                                var checklist = ParseEmbeddedChecklist(checklistEl, stage, order - 1);
                                if (checklist != null)
                                {
                                    _logger.LogDebug("Parsed checklist: {TaskCount} tasks for {StageName}",
                                        checklist.Tasks?.Count ?? 0, stage.Name);
                                    checklists.Add(checklist);
                                }
                                else
                                {
                                    _logger.LogWarning("Failed to parse embedded checklist for stage {StageName}", stage.Name);
                                }
                            }
                            else
                            {
                                _logger.LogWarning("No embedded checklist found for stage {StageName}", stage.Name);
                            }

                            // Parse embedded questionnaire
                            if (stageEl.TryGetProperty("questionnaire", out var questionnaireEl))
                            {
                                var questionnaire = ParseEmbeddedQuestionnaire(questionnaireEl, stage, order - 1);
                                if (questionnaire != null)
                                {
                                    _logger.LogDebug("Parsed questionnaire: {QuestionCount} questions for {StageName}",
                                        questionnaire.Questions?.Count ?? 0, stage.Name);
                                    questionnaires.Add(questionnaire);
                                }
                                else
                                {
                                    _logger.LogWarning("Failed to parse embedded questionnaire for stage {StageName}", stage.Name);
                                }
                            }
                            else
                            {
                                _logger.LogWarning("No embedded questionnaire found for stage {StageName}", stage.Name);
                            }

                            order++;
                        }
                    }

                    var jsonEndTime = DateTime.UtcNow;
                    _logger.LogInformation("JSON parsing succeeded ({Duration:F1}ms) - {StageCount} stages, {ChecklistCount} checklists, {QuestionnaireCount} questionnaires",
                        (jsonEndTime - methodStartTime).TotalMilliseconds, stages.Count, checklists.Count, questionnaires.Count);

                    return new AIWorkflowGenerationResult
                    {
                        Success = true,
                        Message = "Workflow generated successfully with embedded checklists and questionnaires",
                        GeneratedWorkflow = workflow,
                        Stages = stages,
                        Checklists = checklists,
                        Questionnaires = questionnaires,
                        Suggestions = new List<string> { "Consider adding approval stages", "Review stage assignments" }
                    };
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse JSON response, using fallback parsing");
            }

            // Fallback: Generate a basic workflow from the text response
            _logger.LogInformation("Using fallback workflow generation...");
            var fallbackStartTime = DateTime.UtcNow;
            var result = GenerateFallbackWorkflow(aiResponse);
            var fallbackEndTime = DateTime.UtcNow;
            _logger.LogInformation("Fallback completed in {Duration}ms", (fallbackEndTime - fallbackStartTime).TotalMilliseconds);

            var methodEndTime = DateTime.UtcNow;
            _logger.LogInformation("ParseWorkflowResponse completed in {Duration}ms", (methodEndTime - methodStartTime).TotalMilliseconds);

            return result;
        }

        /// <inheritdoc />
        public AIWorkflowGenerationResult? TryRepairAndParseWorkflow(string aiResponse)
        {
            try
            {
                _logger.LogInformation("Attempting to repair potentially corrupted JSON...");

                // Remove possible markdown formatting
                var cleaned = aiResponse
                    .Replace("```json", "")
                    .Replace("```", "")
                    .Trim();

                // Find JSON start and end
                var jsonStart = cleaned.IndexOf('{');
                var jsonEnd = cleaned.LastIndexOf('}');

                if (jsonStart >= 0 && jsonEnd > jsonStart)
                {
                    var jsonContent = cleaned.Substring(jsonStart, jsonEnd - jsonStart + 1);

                    // Try to parse
                    var parsed = JsonSerializer.Deserialize<JsonElement>(jsonContent);

                    // If parsing succeeds, use normal flow
                    return ParseWorkflowFromJsonElement(parsed);
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "JSON repair attempt failed");
            }

            return null;
        }

        /// <inheritdoc />
        public AIWorkflowGenerationResult GenerateFallbackWorkflow(string aiResponse)
        {
            _logger.LogInformation("GenerateFallbackWorkflow started, response length: {Length}", aiResponse.Length);

            var workflow = new WorkflowInputDto
            {
                Name = "AI Generated Workflow",
                Description = "Generated by AI",
                IsActive = true,
                IsAIGenerated = true
            };

            // Intelligently extract stage information from AI response
            _logger.LogInformation("Extracting stages from text...");
            var extractStartTime = DateTime.UtcNow;
            var stages = ExtractStagesFromText(aiResponse);
            var extractEndTime = DateTime.UtcNow;
            _logger.LogInformation("Stage extraction completed in {Duration}ms, found {Count} stages",
                (extractEndTime - extractStartTime).TotalMilliseconds, stages.Count);

            // If no stages extracted, create default stages
            if (!stages.Any())
            {
                stages = new List<AIStageGenerationResult>
                {
                    new AIStageGenerationResult
                    {
                        Name = "Preparation Stage",
                        Description = "Gather required information and resources",
                        Order = 1,
                        AssignedGroup = "Execution Team",
                        EstimatedDuration = 2
                    },
                    new AIStageGenerationResult
                    {
                        Name = "Execution Stage",
                        Description = "Execute main work tasks",
                        Order = 2,
                        AssignedGroup = "Execution Team",
                        EstimatedDuration = 5
                    },
                    new AIStageGenerationResult
                    {
                        Name = "Review Stage",
                        Description = "Review work results and quality",
                        Order = 3,
                        AssignedGroup = "Management Team",
                        EstimatedDuration = 2
                    },
                    new AIStageGenerationResult
                    {
                        Name = "Completion Stage",
                        Description = "Confirm completion and deliver results",
                        Order = 4,
                        AssignedGroup = "Management Team",
                        EstimatedDuration = 1
                    }
                };
            }

            return new AIWorkflowGenerationResult
            {
                Success = true,
                Message = "Workflow generated successfully",
                GeneratedWorkflow = workflow,
                Stages = stages,
                Checklists = new List<AIChecklistGenerationResult>(),
                Questionnaires = new List<AIQuestionnaireGenerationResult>(),
                Suggestions = new List<string> { "Consider adding approval stages", "Review stage assignments" }
            };
        }

        #endregion

        #region Questionnaire Parsing

        /// <inheritdoc />
        public AIQuestionnaireGenerationResult ParseQuestionnaireResponse(string aiResponse)
        {
            var questionnaire = new QuestionnaireInputDto
            {
                Name = "AI Generated Questionnaire",
                Description = "Generated by AI based on requirements",
                IsActive = true
            };

            return new AIQuestionnaireGenerationResult
            {
                Success = true,
                Message = "Questionnaire generated successfully",
                GeneratedQuestionnaire = questionnaire,
                Suggestions = new List<string> { "Review question types", "Add validation rules" }
            };
        }

        /// <inheritdoc />
        public AIQuestionnaireGenerationResult ParseAIQuestionnaireResponse(string aiResponse, AIStageGenerationResult stage)
        {
            try
            {
                // Try to parse JSON response
                if (aiResponse.Contains("{") && aiResponse.Contains("}"))
                {
                    var jsonStart = aiResponse.IndexOf('{');
                    var jsonEnd = aiResponse.LastIndexOf('}') + 1;
                    var jsonContent = aiResponse.Substring(jsonStart, jsonEnd - jsonStart);

                    var parsed = JsonSerializer.Deserialize<JsonElement>(jsonContent);

                    var questions = new List<AIQuestionGenerationResult>();
                    if (parsed.TryGetProperty("questions", out var questionsEl) && questionsEl.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var questionEl in questionsEl.EnumerateArray())
                        {
                            var options = new List<string>();
                            if (questionEl.TryGetProperty("options", out var optionsEl) && optionsEl.ValueKind == JsonValueKind.Array)
                            {
                                foreach (var optionEl in optionsEl.EnumerateArray())
                                {
                                    if (optionEl.ValueKind == JsonValueKind.String)
                                    {
                                        options.Add(optionEl.GetString());
                                    }
                                }
                            }

                            questions.Add(new AIQuestionGenerationResult
                            {
                                Question = questionEl.TryGetProperty("question", out var qEl) ? qEl.GetString() : "Question",
                                Type = questionEl.TryGetProperty("type", out var typeEl) ? typeEl.GetString() : "text",
                                IsRequired = questionEl.TryGetProperty("isRequired", out var reqEl) && reqEl.GetBoolean(),
                                Category = questionEl.TryGetProperty("category", out var catEl) ? catEl.GetString() : "General",
                                Options = options
                            });
                        }
                    }

                    return new AIQuestionnaireGenerationResult
                    {
                        Success = true,
                        Message = $"AI-generated questionnaire for {stage.Name}",
                        GeneratedQuestionnaire = new QuestionnaireInputDto
                        {
                            Name = parsed.TryGetProperty("name", out var nameEl) ? nameEl.GetString() : $"{stage.Name} Questionnaire",
                            Description = parsed.TryGetProperty("description", out var descEl) ? descEl.GetString() : $"AI-generated questionnaire for {stage.Name}",
                            IsActive = true
                        },
                        Questions = questions,
                        ConfidenceScore = 0.9
                    };
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse AI questionnaire response for stage {StageName}", stage.Name);
            }

            // Fallback to default generation
            return GenerateFallbackQuestionnaire(stage);
        }

        /// <inheritdoc />
        public List<AIQuestionnaireGenerationResult>? ParseBatchQuestionnaireResponse(string aiResponse, List<AIStageGenerationResult> stages)
        {
            try
            {
                // Try to parse JSON response
                if (aiResponse.Contains("{") && aiResponse.Contains("}"))
                {
                    var jsonStart = aiResponse.IndexOf('{');
                    var jsonEnd = aiResponse.LastIndexOf('}') + 1;
                    var jsonContent = aiResponse.Substring(jsonStart, jsonEnd - jsonStart);

                    var parsed = JsonSerializer.Deserialize<JsonElement>(jsonContent);
                    var results = new List<AIQuestionnaireGenerationResult>();

                    if (parsed.TryGetProperty("questionnaires", out var questionnairesEl) && questionnairesEl.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var questionnaireEl in questionnairesEl.EnumerateArray())
                        {
                            if (questionnaireEl.TryGetProperty("stageIndex", out var indexEl) && indexEl.TryGetInt32(out var stageIndex)
                                && stageIndex >= 0 && stageIndex < stages.Count)
                            {
                                var stage = stages[stageIndex];
                                var questions = new List<AIQuestionGenerationResult>();

                                if (questionnaireEl.TryGetProperty("questions", out var questionsEl) && questionsEl.ValueKind == JsonValueKind.Array)
                                {
                                    foreach (var questionEl in questionsEl.EnumerateArray())
                                    {
                                        var options = new List<string>();
                                        if (questionEl.TryGetProperty("options", out var optionsEl) && optionsEl.ValueKind == JsonValueKind.Array)
                                        {
                                            foreach (var optionEl in optionsEl.EnumerateArray())
                                            {
                                                if (optionEl.ValueKind == JsonValueKind.String)
                                                {
                                                    options.Add(optionEl.GetString());
                                                }
                                            }
                                        }

                                        questions.Add(new AIQuestionGenerationResult
                                        {
                                            Question = questionEl.TryGetProperty("question", out var qEl) ? qEl.GetString() : "Question",
                                            Type = questionEl.TryGetProperty("type", out var typeEl) ? typeEl.GetString() : "text",
                                            IsRequired = questionEl.TryGetProperty("isRequired", out var reqEl) && reqEl.GetBoolean(),
                                            Category = questionEl.TryGetProperty("category", out var catEl) ? catEl.GetString() : "General",
                                            Options = options
                                        });
                                    }
                                }

                                results.Add(new AIQuestionnaireGenerationResult
                                {
                                    Success = true,
                                    Message = $"Batch AI-generated questionnaire for {stage.Name}",
                                    GeneratedQuestionnaire = new QuestionnaireInputDto
                                    {
                                        Name = questionnaireEl.TryGetProperty("name", out var nameEl) ? nameEl.GetString() : $"{stage.Name} Questionnaire",
                                        Description = questionnaireEl.TryGetProperty("description", out var descEl) ? descEl.GetString() : $"AI-generated questionnaire for {stage.Name}",
                                        IsActive = true
                                    },
                                    Questions = questions,
                                    ConfidenceScore = 0.95 // Higher confidence for batch generation
                                });
                            }
                        }
                    }

                    // Ensure result count matches stages, fill missing with fallback
                    while (results.Count < stages.Count)
                    {
                        var missingStage = stages[results.Count];
                        results.Add(GenerateFallbackQuestionnaire(missingStage));
                    }

                    return results;
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse batch questionnaire response");
            }

            return null;
        }

        #endregion

        #region Checklist Parsing

        /// <inheritdoc />
        public AIChecklistGenerationResult ParseChecklistResponse(string aiResponse)
        {
            var checklist = new ChecklistInputDto
            {
                Name = "AI Generated Checklist",
                Description = "Generated by AI based on requirements",
                Team = "General"
            };

            return new AIChecklistGenerationResult
            {
                Success = true,
                Message = "Checklist generated successfully",
                GeneratedChecklist = checklist,
                Suggestions = new List<string> { "Review task dependencies", "Adjust time estimates" }
            };
        }

        /// <inheritdoc />
        public AIChecklistGenerationResult ParseAIChecklistResponse(string aiResponse, AIStageGenerationResult stage)
        {
            try
            {
                // Try to parse JSON response
                if (aiResponse.Contains("{") && aiResponse.Contains("}"))
                {
                    var jsonStart = aiResponse.IndexOf('{');
                    var jsonEnd = aiResponse.LastIndexOf('}') + 1;
                    var jsonContent = aiResponse.Substring(jsonStart, jsonEnd - jsonStart);

                    var parsed = JsonSerializer.Deserialize<JsonElement>(jsonContent);

                    var tasks = new List<AITaskGenerationResult>();
                    if (parsed.TryGetProperty("tasks", out var tasksEl) && tasksEl.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var taskEl in tasksEl.EnumerateArray())
                        {
                            tasks.Add(new AITaskGenerationResult
                            {
                                Title = taskEl.TryGetProperty("title", out var titleEl) ? titleEl.GetString() : "Task",
                                Description = taskEl.TryGetProperty("description", out var taskDescEl) ? taskDescEl.GetString() : "",
                                IsRequired = taskEl.TryGetProperty("isRequired", out var reqEl) && reqEl.GetBoolean(),
                                EstimatedMinutes = taskEl.TryGetProperty("estimatedMinutes", out var timeEl) && timeEl.TryGetInt32(out var minutes) ? minutes : 60,
                                Category = taskEl.TryGetProperty("category", out var catEl) ? catEl.GetString() : "General"
                            });
                        }
                    }

                    return new AIChecklistGenerationResult
                    {
                        Success = true,
                        Message = $"AI-generated checklist for {stage.Name}",
                        GeneratedChecklist = new ChecklistInputDto
                        {
                            Name = parsed.TryGetProperty("name", out var nameEl) ? nameEl.GetString() : $"{stage.Name} Checklist",
                            Description = parsed.TryGetProperty("description", out var descEl) ? descEl.GetString() : $"AI-generated checklist for {stage.Name}",
                            Team = stage.AssignedGroup,
                            IsActive = true
                        },
                        Tasks = tasks,
                        ConfidenceScore = 0.9
                    };
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse AI checklist response for stage {StageName}", stage.Name);
            }

            // Fallback to default generation
            return GenerateFallbackChecklist(stage);
        }

        /// <inheritdoc />
        public List<AIChecklistGenerationResult>? ParseBatchChecklistResponse(string aiResponse, List<AIStageGenerationResult> stages)
        {
            try
            {
                _logger.LogInformation("Parsing batch checklist response, length: {Length}", aiResponse.Length);

                // Try to parse JSON response
                if (aiResponse.Contains("{") && aiResponse.Contains("}"))
                {
                    var jsonStart = aiResponse.IndexOf('{');
                    var jsonEnd = aiResponse.LastIndexOf('}') + 1;
                    var jsonContent = aiResponse.Substring(jsonStart, jsonEnd - jsonStart);

                    _logger.LogInformation("Extracted JSON content: {JsonContent}",
                        jsonContent.Length > 1000 ? jsonContent.Substring(0, 1000) + "..." : jsonContent);

                    var parsed = JsonSerializer.Deserialize<JsonElement>(jsonContent);
                    var results = new List<AIChecklistGenerationResult>();

                    if (parsed.TryGetProperty("checklists", out var checklistsEl) && checklistsEl.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var checklistEl in checklistsEl.EnumerateArray())
                        {
                            if (checklistEl.TryGetProperty("stageIndex", out var indexEl) && indexEl.TryGetInt32(out var stageIndex)
                                && stageIndex >= 0 && stageIndex < stages.Count)
                            {
                                var stage = stages[stageIndex];
                                var tasks = new List<AITaskGenerationResult>();

                                if (checklistEl.TryGetProperty("tasks", out var tasksEl) && tasksEl.ValueKind == JsonValueKind.Array)
                                {
                                    foreach (var taskEl in tasksEl.EnumerateArray())
                                    {
                                        tasks.Add(new AITaskGenerationResult
                                        {
                                            Title = taskEl.TryGetProperty("title", out var titleEl) ? titleEl.GetString() : "Task",
                                            Description = taskEl.TryGetProperty("description", out var taskDescEl) ? taskDescEl.GetString() : "",
                                            IsRequired = taskEl.TryGetProperty("isRequired", out var reqEl) && reqEl.GetBoolean(),
                                            EstimatedMinutes = taskEl.TryGetProperty("estimatedMinutes", out var timeEl) && timeEl.TryGetInt32(out var minutes) ? minutes : 60,
                                            Category = taskEl.TryGetProperty("category", out var catEl) ? catEl.GetString() : "General"
                                        });
                                    }
                                }

                                results.Add(new AIChecklistGenerationResult
                                {
                                    Success = true,
                                    Message = $"Batch AI-generated checklist for {stage.Name}",
                                    GeneratedChecklist = new ChecklistInputDto
                                    {
                                        Name = checklistEl.TryGetProperty("name", out var nameEl) ? nameEl.GetString() : $"{stage.Name} Checklist",
                                        Description = checklistEl.TryGetProperty("description", out var descEl) ? descEl.GetString() : $"AI-generated checklist for {stage.Name}",
                                        Team = stage.AssignedGroup,
                                        IsActive = true
                                    },
                                    Tasks = tasks,
                                    ConfidenceScore = 0.95 // Higher confidence for batch generation
                                });
                            }
                        }
                    }

                    // Ensure result count matches stages, fill missing with fallback
                    while (results.Count < stages.Count)
                    {
                        var missingStage = stages[results.Count];
                        results.Add(GenerateFallbackChecklist(missingStage));
                    }

                    return results;
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse batch checklist response");
            }

            return null;
        }

        #endregion

        #region Chat Parsing

        /// <inheritdoc />
        public AIChatResponse ParseChatResponse(string content, AIChatInput input)
        {
            // Analyze the response to determine if conversation is complete
            var isComplete = DetermineChatCompletion(content, input);

            return new AIChatResponse
            {
                Success = true,
                Message = "Chat response generated successfully",
                Response = new AIChatResponseData
                {
                    Content = content,
                    IsComplete = isComplete,
                    Suggestions = ExtractSuggestions(content),
                    NextQuestions = ExtractNextQuestions(content)
                },
                SessionId = input.SessionId
            };
        }

        /// <inheritdoc />
        public AIChatResponse GenerateFallbackChatResponse(AIChatInput input)
        {
            var userMessageCount = input.Messages.Count(m => m.Role == "user");

            string fallbackContent = userMessageCount switch
            {
                1 => "I'm currently experiencing some technical issues with the AI service. However, I'd be happy to help you with your workflow! Could you tell me more about the teams or people who will be involved in this process?",
                2 => "Thanks for the details! While I'm working through some technical issues, I can still assist you. How many main stages or steps do you think this workflow should have? And what's your expected timeline?",
                3 => "Great information! Despite some temporary service issues, I'm here to help. Are there any specific requirements, documents, or approvals that need to be included in this workflow?",
                _ => "Thank you for all the information! Even with current technical challenges, I believe we have enough details to help you create a comprehensive workflow. Would you like to proceed?"
            };

            var suggestions = new List<string>
            {
                "Continue describing your workflow requirements",
                "Try again in a few moments",
                "Check if your AI model configuration is correct"
            };

            var nextQuestions = userMessageCount switch
            {
                1 => new List<string> { "Who are the key stakeholders?", "What is the main goal of this workflow?" },
                2 => new List<string> { "What are the key milestones?", "Are there any critical dependencies?" },
                3 => new List<string> { "What documents need approval?", "Who has decision-making authority?" },
                _ => new List<string> { "Ready to generate the workflow?", "Any final requirements to add?" }
            };

            return new AIChatResponse
            {
                Success = true,
                Message = "AI service temporarily unavailable, using intelligent fallback response",
                Response = new AIChatResponseData
                {
                    Content = fallbackContent,
                    IsComplete = userMessageCount >= 4,
                    Suggestions = suggestions,
                    NextQuestions = nextQuestions
                },
                SessionId = input.SessionId
            };
        }

        /// <inheritdoc />
        public AIChatResponse GenerateErrorChatResponse(AIChatInput input, string errorMessage)
        {
            var isModelNotFoundError = errorMessage.Contains("model_not_found") || errorMessage.Contains("does not exist");
            var isAuthError = errorMessage.Contains("Unauthorized") || errorMessage.Contains("authentication");

            string errorContent;
            List<string> errorSuggestions;

            if (isModelNotFoundError)
            {
                errorContent = "I'm having trouble accessing the specified AI model. This might be because the model doesn't exist or your API key doesn't have access to it. I'll try to help you with an alternative approach.";
                errorSuggestions = new List<string>
                {
                    "Check your AI model configuration",
                    "Verify your API key permissions",
                    "Try using a different model (e.g., gpt-3.5-turbo)",
                    "Continue with manual workflow creation"
                };
            }
            else if (isAuthError)
            {
                errorContent = "There seems to be an authentication issue with the AI service. Please check your API configuration.";
                errorSuggestions = new List<string>
                {
                    "Verify your API key is correct",
                    "Check if your API key has expired",
                    "Ensure your account has sufficient credits"
                };
            }
            else
            {
                errorContent = "I'm experiencing technical difficulties right now. Let me try to assist you manually while we resolve this issue.";
                errorSuggestions = new List<string>
                {
                    "Try again in a few moments",
                    "Continue describing your workflow manually",
                    "Check system status and try again"
                };
            }

            return new AIChatResponse
            {
                Success = false,
                Message = $"AI service error: {errorMessage}",
                Response = new AIChatResponseData
                {
                    Content = errorContent,
                    IsComplete = false,
                    Suggestions = errorSuggestions,
                    NextQuestions = new List<string>
                    {
                        "Would you like to continue manually?",
                        "Should I help you configure a different AI model?"
                    }
                },
                SessionId = input.SessionId
            };
        }

        #endregion

        #region Summary Parsing

        /// <inheritdoc />
        public AIStageSummaryResult ParseStageSummaryResponse(string aiResponse, AIStageSummaryInput input)
        {
            try
            {
                // Try to extract JSON from the response
                var jsonMatch = Regex.Match(aiResponse, @"\{.*\}", RegexOptions.Singleline);
                if (jsonMatch.Success)
                {
                    var jsonContent = jsonMatch.Value;
                    var summaryData = JsonSerializer.Deserialize<JsonElement>(jsonContent);

                    var result = new AIStageSummaryResult
                    {
                        Success = true,
                        Message = "Summary generated successfully",
                        ConfidenceScore = 0.85 // Default confidence score
                    };

                    // Extract main summary
                    if (summaryData.TryGetProperty("summary", out var summaryElement))
                    {
                        result.Summary = summaryElement.GetString() ?? "";
                    }

                    // Extract breakdown with new structure
                    if (summaryData.TryGetProperty("breakdown", out var breakdownElement))
                    {
                        result.Breakdown = new AIStageSummaryBreakdown
                        {
                            Overview = breakdownElement.TryGetProperty("stageOverview", out var stageOverviewEl) ? stageOverviewEl.GetString() ?? "" : "",
                            ChecklistSummary = breakdownElement.TryGetProperty("checklistSummary", out var checklistEl) ? checklistEl.GetString() ?? "" : "",
                            QuestionnaireSummary = breakdownElement.TryGetProperty("questionnaireSummary", out var questionnaireEl) ? questionnaireEl.GetString() ?? "" : "",
                            ProgressAnalysis = breakdownElement.TryGetProperty("fieldsSummary", out var fieldsEl) ? fieldsEl.GetString() ?? "" : "",
                            RiskAssessment = "" // Not used anymore
                        };
                    }

                    // Initialize empty collections for removed features
                    result.KeyInsights = new List<string>();
                    result.Recommendations = new List<string>();
                    result.CompletionStatus = null;

                    return result;
                }
                else
                {
                    // Fallback: use the entire response as summary
                    return new AIStageSummaryResult
                    {
                        Success = true,
                        Message = "Summary generated successfully (fallback format)",
                        Summary = aiResponse,
                        ConfidenceScore = 0.6
                    };
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error parsing AI summary response: {Error}", ex.Message);

                // Fallback: return the raw response
                return new AIStageSummaryResult
                {
                    Success = true,
                    Message = "Summary generated with parsing issues",
                    Summary = aiResponse,
                    ConfidenceScore = 0.4
                };
            }
        }

        #endregion

        #region Utility

        /// <inheritdoc />
        public string FixJsonContent(string jsonContent)
        {
            if (string.IsNullOrEmpty(jsonContent))
                return jsonContent;

            var result = jsonContent;

            try
            {
                // Fix unquoted property names in objects (e.g., {id: "1"} -> {"id": "1"})
                result = Regex.Replace(
                    result,
                    @"(?<=[{,]\s*)([a-zA-Z_][a-zA-Z0-9_]*)\s*:",
                    "\"$1\":");

                // Fix single quotes to double quotes
                result = result.Replace("'", "\"");

                // Fix trailing commas before closing brackets
                result = Regex.Replace(result, @",\s*}", "}");
                result = Regex.Replace(result, @",\s*\]", "]");

                // Fix missing commas between array elements (common AI mistake)
                // e.g., }{ -> },{
                result = Regex.Replace(result, @"}\s*{", "},{");

                _logger.LogDebug("JSON content fixed");
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to fix JSON content, using original");
            }

            return result;
        }

        /// <inheritdoc />
        public List<QuestionOptionDto> ParseQuestionOptions(List<string> options, int questionIndex)
        {
            if (options == null || !options.Any())
                return new List<QuestionOptionDto>();

            var result = new List<QuestionOptionDto>();
            var optionIndex = 1;

            foreach (var opt in options)
            {
                if (string.IsNullOrEmpty(opt))
                    continue;

                try
                {
                    // Try to parse as JSON object first
                    if (opt.TrimStart().StartsWith("{"))
                    {
                        var optionObj = JsonSerializer.Deserialize<JsonElement>(opt);
                        var id = optionObj.TryGetProperty("id", out var idEl) ? idEl.GetString() : optionIndex.ToString();
                        var value = optionObj.TryGetProperty("value", out var valEl) ? valEl.GetString() : opt;
                        var label = optionObj.TryGetProperty("label", out var labelEl) ? labelEl.GetString() : value;

                        result.Add(new QuestionOptionDto
                        {
                            Id = id,
                            Label = label,
                            Value = value,
                            Order = optionIndex
                        });
                    }
                    else
                    {
                        // Plain string format
                        result.Add(new QuestionOptionDto
                        {
                            Id = optionIndex.ToString(),
                            Label = opt,
                            Value = opt,
                            Order = optionIndex
                        });
                    }
                }
                catch (Exception ex)
                {
                    // Fallback to plain string, log for debugging
                    _logger.LogDebug(ex, "Failed to parse option");
                    result.Add(new QuestionOptionDto
                    {
                        Id = optionIndex.ToString(),
                        Label = opt,
                        Value = opt,
                        Order = optionIndex
                    });
                }

                optionIndex++;
            }

            return result;
        }

        /// <summary>
        /// Determine the effective language for summary generation based on input content
        /// </summary>
        /// <param name="input">Stage summary input</param>
        /// <returns>Language code (e.g., "zh-CN" or "en-US")</returns>
        public static string DetermineEffectiveLanguage(AIStageSummaryInput input)
        {
            var lang = input.Language?.Trim();
            if (!string.IsNullOrWhiteSpace(lang) && !string.Equals(lang, "auto", StringComparison.OrdinalIgnoreCase))
            {
                return lang;
            }

            // Collect text content for heuristic detection
            var sb = new StringBuilder();
            if (!string.IsNullOrWhiteSpace(input.StageName)) sb.Append(input.StageName);
            if (!string.IsNullOrWhiteSpace(input.StageDescription)) sb.Append(input.StageDescription);
            if (input.ChecklistTasks != null)
            {
                foreach (var t in input.ChecklistTasks)
                {
                    if (!string.IsNullOrWhiteSpace(t.TaskName)) sb.Append(t.TaskName);
                    if (!string.IsNullOrWhiteSpace(t.Description)) sb.Append(t.Description);
                    if (!string.IsNullOrWhiteSpace(t.CompletionNotes)) sb.Append(t.CompletionNotes);
                }
            }
            if (input.QuestionnaireQuestions != null)
            {
                foreach (var q in input.QuestionnaireQuestions)
                {
                    if (!string.IsNullOrWhiteSpace(q.QuestionText)) sb.Append(q.QuestionText);
                    if (q.Answer != null) sb.Append(q.Answer?.ToString());
                }
            }

            var combined = sb.ToString();
            return ContainsCjk(combined) ? "zh-CN" : "en-US";
        }

        /// <summary>
        /// Detect if a string contains CJK (Chinese) characters
        /// </summary>
        /// <param name="text">Text to check</param>
        /// <returns>True if the text contains CJK characters</returns>
        public static bool ContainsCjk(string text)
        {
            if (string.IsNullOrEmpty(text)) return false;
            // Basic CJK Unified Ideographs range
            return Regex.IsMatch(text, "[\\u4e00-\\u9fff]");
        }

        #endregion

        #region Confidence Scoring

        /// <inheritdoc />
        public double CalculateConfidenceScore(WorkflowInputDto workflow)
        {
            double score = 0.5; // Base score

            if (!string.IsNullOrEmpty(workflow.Name)) score += 0.2;
            if (!string.IsNullOrEmpty(workflow.Description)) score += 0.2;

            return Math.Min(score, 1.0);
        }

        /// <inheritdoc />
        public double CalculateQuestionnaireConfidenceScore(QuestionnaireInputDto questionnaire)
        {
            double score = 0.5;
            if (!string.IsNullOrEmpty(questionnaire.Name)) score += 0.25;
            if (!string.IsNullOrEmpty(questionnaire.Description)) score += 0.25;
            return Math.Min(score, 1.0);
        }

        /// <inheritdoc />
        public double CalculateChecklistConfidenceScore(ChecklistInputDto checklist)
        {
            double score = 0.5;
            if (!string.IsNullOrEmpty(checklist.Name)) score += 0.25;
            if (!string.IsNullOrEmpty(checklist.Description)) score += 0.25;
            return Math.Min(score, 1.0);
        }

        /// <inheritdoc />
        public double CalculateWorkflowQualityScore(WorkflowInputDto workflow, List<AIValidationIssue> issues)
        {
            double score = 1.0;

            foreach (var issue in issues)
            {
                switch (issue.Severity)
                {
                    case "Error":
                        score -= 0.3;
                        break;
                    case "Warning":
                        score -= 0.1;
                        break;
                }
            }

            return Math.Max(score, 0.0);
        }

        #endregion

        #region Private Helper Methods

        /// <summary>
        /// Parse a workflow from a JsonElement (used by TryRepairAndParseWorkflow)
        /// </summary>
        private AIWorkflowGenerationResult ParseWorkflowFromJsonElement(JsonElement parsed)
        {
            var workflow = new WorkflowInputDto
            {
                Name = parsed.TryGetProperty("name", out var nameEl) ? nameEl.GetString() : "AI Generated Workflow",
                Description = parsed.TryGetProperty("description", out var descEl) ? descEl.GetString() : "Generated by AI",
                IsActive = true,
                IsAIGenerated = true
            };

            var stages = new List<AIStageGenerationResult>();
            var checklists = new List<AIChecklistGenerationResult>();
            var questionnaires = new List<AIQuestionnaireGenerationResult>();

            if (parsed.TryGetProperty("stages", out var stagesEl) && stagesEl.ValueKind == JsonValueKind.Array)
            {
                var order = 1;
                foreach (var stageEl in stagesEl.EnumerateArray())
                {
                    var stage = new AIStageGenerationResult
                    {
                        Name = stageEl.TryGetProperty("name", out var sNameEl) ? sNameEl.GetString() : $"Stage {order}",
                        Description = stageEl.TryGetProperty("description", out var sDescEl) ? sDescEl.GetString() : "",
                        Order = order,
                        AssignedGroup = stageEl.TryGetProperty("assignedGroup", out var sGroupEl) ? sGroupEl.GetString() : "General",
                        EstimatedDuration = stageEl.TryGetProperty("estimatedDuration", out var sDurEl) && sDurEl.TryGetInt32(out var dur) ? dur : 1
                    };
                    stages.Add(stage);

                    // Parse embedded checklist
                    if (stageEl.TryGetProperty("checklist", out var checklistEl))
                    {
                        var checklist = ParseEmbeddedChecklist(checklistEl, stage, order - 1);
                        if (checklist != null)
                        {
                            checklists.Add(checklist);
                        }
                    }

                    // Parse embedded questionnaire
                    if (stageEl.TryGetProperty("questionnaire", out var questionnaireEl))
                    {
                        var questionnaire = ParseEmbeddedQuestionnaire(questionnaireEl, stage, order - 1);
                        if (questionnaire != null)
                        {
                            questionnaires.Add(questionnaire);
                        }
                    }

                    order++;
                }
            }

            return new AIWorkflowGenerationResult
            {
                Success = true,
                Message = "Workflow generated successfully after JSON repair",
                GeneratedWorkflow = workflow,
                Stages = stages,
                Checklists = checklists,
                Questionnaires = questionnaires,
                Suggestions = new List<string> { "Consider adding approval stages", "Review stage assignments" }
            };
        }

        /// <summary>
        /// Parse embedded checklist from a stage JSON element
        /// </summary>
        private AIChecklistGenerationResult? ParseEmbeddedChecklist(JsonElement checklistEl, AIStageGenerationResult stage, int stageIndex)
        {
            try
            {
                var tasks = new List<AITaskGenerationResult>();

                if (checklistEl.TryGetProperty("tasks", out var tasksEl) && tasksEl.ValueKind == JsonValueKind.Array)
                {
                    foreach (var taskEl in tasksEl.EnumerateArray())
                    {
                        var task = new AITaskGenerationResult
                        {
                            Title = taskEl.TryGetProperty("title", out var titleEl) ? titleEl.GetString() : "Task",
                            Description = taskEl.TryGetProperty("description", out var taskDescEl) ? taskDescEl.GetString() : "",
                            IsRequired = taskEl.TryGetProperty("isRequired", out var reqEl) && reqEl.GetBoolean(),
                            EstimatedMinutes = taskEl.TryGetProperty("estimatedMinutes", out var minEl) && minEl.TryGetInt32(out var minutes) ? minutes : 60,
                            Category = taskEl.TryGetProperty("category", out var catEl) ? catEl.GetString() : "General"
                        };
                        tasks.Add(task);
                    }
                }

                return new AIChecklistGenerationResult
                {
                    Success = true,
                    Message = "Checklist generated successfully",
                    StageName = stage.Name,
                    StageOrder = stageIndex + 1,
                    GeneratedChecklist = new ChecklistInputDto
                    {
                        Name = checklistEl.TryGetProperty("name", out var nameEl) ? nameEl.GetString() : $"Checklist for {stage.Name}",
                        Description = checklistEl.TryGetProperty("description", out var checklistDescEl) ? checklistDescEl.GetString() : $"Tasks for {stage.Name}"
                    },
                    Tasks = tasks
                };
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse embedded checklist for stage {StageName}", stage.Name);
                return GenerateFallbackChecklist(stage);
            }
        }

        /// <summary>
        /// Parse embedded questionnaire from a stage JSON element
        /// </summary>
        private AIQuestionnaireGenerationResult? ParseEmbeddedQuestionnaire(JsonElement questionnaireEl, AIStageGenerationResult stage, int stageIndex)
        {
            try
            {
                var questions = new List<AIQuestionGenerationResult>();

                if (questionnaireEl.TryGetProperty("questions", out var questionsEl) && questionsEl.ValueKind == JsonValueKind.Array)
                {
                    foreach (var questionEl in questionsEl.EnumerateArray())
                    {
                        var question = new AIQuestionGenerationResult
                        {
                            Question = questionEl.TryGetProperty("question", out var qEl) ? qEl.GetString() : "Question",
                            Type = questionEl.TryGetProperty("type", out var typeEl) ? typeEl.GetString() : "short_answer",
                            IsRequired = questionEl.TryGetProperty("isRequired", out var reqEl) && reqEl.GetBoolean(),
                            Category = questionEl.TryGetProperty("category", out var catEl) ? catEl.GetString() : "General"
                        };

                        // Handle options for multiple_choice, checkboxes, dropdown types
                        if ((question.Type == "multiple_choice" || question.Type == "checkboxes" || question.Type == "dropdown" ||
                             question.Type == "select" || question.Type == "multiselect") &&
                            questionEl.TryGetProperty("options", out var optionsEl) && optionsEl.ValueKind == JsonValueKind.Array)
                        {
                            var options = new List<string>();
                            var optionIndex = 1;
                            foreach (var optionEl in optionsEl.EnumerateArray())
                            {
                                if (optionEl.ValueKind == JsonValueKind.String)
                                {
                                    // Simple string format: ["option1", "option2"]
                                    options.Add(optionEl.GetString());
                                }
                                else if (optionEl.ValueKind == JsonValueKind.Object)
                                {
                                    // Object format: [{"id": "1", "value": "val", "label": "Label"}]
                                    var optionObj = new Dictionary<string, string>
                                    {
                                        ["id"] = optionEl.TryGetProperty("id", out var idEl) ? idEl.GetString() : optionIndex.ToString(),
                                        ["value"] = optionEl.TryGetProperty("value", out var valEl) ? valEl.GetString() : $"option{optionIndex}",
                                        ["label"] = optionEl.TryGetProperty("label", out var labelEl) ? labelEl.GetString() : $"Option {optionIndex}"
                                    };
                                    options.Add(JsonSerializer.Serialize(optionObj));
                                }
                                optionIndex++;
                            }
                            question.Options = options;
                        }

                        questions.Add(question);
                    }
                }

                return new AIQuestionnaireGenerationResult
                {
                    Success = true,
                    Message = "Questionnaire generated successfully",
                    StageName = stage.Name,
                    StageOrder = stageIndex + 1,
                    GeneratedQuestionnaire = new QuestionnaireInputDto
                    {
                        Name = questionnaireEl.TryGetProperty("name", out var nameEl) ? nameEl.GetString() : $"Questionnaire for {stage.Name}",
                        Description = questionnaireEl.TryGetProperty("description", out var questionnaireDescEl) ? questionnaireDescEl.GetString() : $"Information gathering for {stage.Name}"
                    },
                    Questions = questions
                };
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to parse embedded questionnaire for stage {StageName}", stage.Name);
                return GenerateFallbackQuestionnaire(stage);
            }
        }

        /// <summary>
        /// Determine if a chat conversation is complete based on content analysis
        /// </summary>
        private static bool DetermineChatCompletion(string content, AIChatInput input)
        {
            // Simple heuristics to determine if conversation is complete
            var completionKeywords = new[] { "enough information", "ready to create", "comprehensive workflow", "proceed with generation" };
            var lowerContent = content.ToLower();

            return completionKeywords.Any(keyword => lowerContent.Contains(keyword)) ||
                   input.Messages.Count(m => m.Role == "user") >= 4;
        }

        /// <summary>
        /// Extract suggestions from AI response content
        /// </summary>
        private static List<string> ExtractSuggestions(string content)
        {
            var suggestions = new List<string>();

            if (content.Contains("consider", StringComparison.OrdinalIgnoreCase))
            {
                suggestions.Add("Consider the suggestions mentioned in the response");
            }

            return suggestions;
        }

        /// <summary>
        /// Extract follow-up questions from AI response content
        /// </summary>
        private static List<string> ExtractNextQuestions(string content)
        {
            var questions = new List<string>();
            var sentences = content.Split('.', '?', '!');

            foreach (var sentence in sentences)
            {
                if (sentence.Trim().Contains('?'))
                {
                    questions.Add(sentence.Trim() + "?");
                }
            }

            return questions.Take(2).ToList(); // Limit to 2 questions
        }

        /// <summary>
        /// Extract stages from text content when JSON parsing fails
        /// </summary>
        private List<AIStageGenerationResult> ExtractStagesFromText(string text)
        {
            _logger.LogInformation("ExtractStagesFromText started, text length: {Length}", text.Length);

            var stages = new List<AIStageGenerationResult>();
            var lines = text.Split('\n', StringSplitOptions.RemoveEmptyEntries);
            var order = 1;

            _logger.LogInformation("Processing {LineCount} lines of text", lines.Length);

            foreach (var line in lines)
            {
                var trimmedLine = line.Trim();

                // Find possible stage identifiers
                if (trimmedLine.Contains("阶段") || trimmedLine.Contains("步骤") ||
                    trimmedLine.Contains("Stage") || trimmedLine.Contains("Step") ||
                    trimmedLine.StartsWith("-") || trimmedLine.StartsWith("*") ||
                    Regex.IsMatch(trimmedLine, @"^\d+\."))
                {
                    var stageName = ExtractStageName(trimmedLine);
                    if (!string.IsNullOrEmpty(stageName) && stageName.Length > 2)
                    {
                        stages.Add(new AIStageGenerationResult
                        {
                            Name = stageName,
                            Description = $"AI-generated {stageName}",
                            Order = order++,
                            AssignedGroup = "Execution Team",
                            EstimatedDuration = 2
                        });
                    }
                }
            }

            return stages;
        }

        /// <summary>
        /// Extract a clean stage name from a text line
        /// </summary>
        private static string ExtractStageName(string line)
        {
            // Remove common prefixes and identifiers
            var cleaned = line.Trim()
                .Replace("-", "")
                .Replace("*", "")
                .Replace("•", "");

            // Remove numeric prefixes (e.g., "1. ", "2. ")
            cleaned = Regex.Replace(cleaned, @"^\d+\.\s*", "");

            // Remove parentheses content
            cleaned = Regex.Replace(cleaned, @"\([^)]*\)", "");

            return cleaned.Trim();
        }

        /// <summary>
        /// Generate a fallback checklist for a stage when parsing fails
        /// </summary>
        private static AIChecklistGenerationResult GenerateFallbackChecklist(AIStageGenerationResult stage)
        {
            return new AIChecklistGenerationResult
            {
                Success = true,
                Message = $"Empty checklist for {stage.Name} - no AI tasks generated",
                GeneratedChecklist = new ChecklistInputDto
                {
                    Name = $"{stage.Name} Checklist",
                    Description = $"Tasks for {stage.Name}",
                    Team = stage.AssignedGroup,
                    IsActive = true
                },
                Tasks = new List<AITaskGenerationResult>(),
                ConfidenceScore = 0.0
            };
        }

        /// <summary>
        /// Generate a fallback questionnaire for a stage when parsing fails
        /// </summary>
        private static AIQuestionnaireGenerationResult GenerateFallbackQuestionnaire(AIStageGenerationResult stage)
        {
            return new AIQuestionnaireGenerationResult
            {
                Success = true,
                Message = $"Empty questionnaire for {stage.Name} - no AI questions generated",
                GeneratedQuestionnaire = new QuestionnaireInputDto
                {
                    Name = $"{stage.Name} Questionnaire",
                    Description = $"Information gathering for {stage.Name}",
                    IsActive = true
                },
                Questions = new List<AIQuestionGenerationResult>(),
                ConfidenceScore = 0.0
            };
        }

        #endregion

        #region Requirements Parsing

        /// <inheritdoc />
        public AIRequirementsParsingResult ParseRequirementsResponse(string aiResponse)
        {
            try
            {
                // Parse the AI response and extract requirements
                var requirements = new AIRequirements
                {
                    ProcessType = "General",
                    Stakeholders = new List<string> { "User", "Manager" },
                    Steps = new List<string> { "Start", "Process", "End" },
                    Approvals = new List<string>(),
                    Notifications = new List<string>()
                };

                return new AIRequirementsParsingResult
                {
                    Success = true,
                    Message = "Requirements parsed successfully",
                    Requirements = requirements
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to parse requirements response");
                return new AIRequirementsParsingResult
                {
                    Success = false,
                    Message = $"Failed to parse requirements: {ex.Message}"
                };
            }
        }

        #endregion
    }
}
