using System.ComponentModel.DataAnnotations;
using FlowFlex.Domain.Entities.Base;
using SqlSugar;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FlowFlex.Domain.Entities.Action
{
    /// <summary>
    /// Action Definition Entity - Store basic information and configuration of Actions
    /// </summary>
    [SugarTable("ff_action_definitions")]
    public class ActionDefinition : EntityBaseCreateInfo
    {
        /// <summary>
        /// Action name
        /// </summary>
        [Required]
        [StringLength(20)]
        [SugarColumn(ColumnName = "action_code")]
        public string ActionCode { get; set; } = string.Empty;

        /// <summary>
        /// Action name
        /// </summary>
        [Required]
        [StringLength(100)]
        [SugarColumn(ColumnName = "action_name")]
        public string ActionName { get; set; } = string.Empty;

        /// <summary>
        /// Action type (Python, HttpApi, SendEmail)
        /// </summary>
        [Required]
        [StringLength(50)]
        [SugarColumn(ColumnName = "action_type")]
        public string ActionType { get; set; } = string.Empty;

        /// <summary>
        /// Action description
        /// </summary>
        [StringLength(500)]
        [SugarColumn(ColumnName = "description")]
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Action configuration (JSON format, contains execution parameters)
        /// </summary>
        [SugarColumn(ColumnName = "action_config", ColumnDataType = "jsonb", IsJson = true)]
        public JToken ActionConfig { get; set; } = new JObject();

        /// <summary>
        /// Whether this action is enabled
        /// </summary>
        [SugarColumn(ColumnName = "is_enabled")]
        public bool IsEnabled { get; set; } = true;

        [SugarColumn(ColumnName = "is_tools")]
        public bool IsTools { get; set; } = false;

        /// <summary>
        /// Whether this action was generated by AI
        /// </summary>
        [SugarColumn(ColumnName = "is_ai_generated")]
        public bool IsAIGenerated { get; set; } = false;

        /// <summary>
        /// Trigger type for the action (Stage, Task, Question, Workflow, Integration)
        /// Defines where this action can be used or triggered
        /// </summary>
        [StringLength(50)]
        [SugarColumn(ColumnName = "trigger_type")]
        public string TriggerType { get; set; }
    }
}