/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIModelConfigManager: typeof import('./src/components/ai/AIModelConfigManager.vue')['default']
    AIWorkflowGenerator: typeof import('./src/components/ai/AIWorkflowGenerator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
